version: 1.0

jobs:
  test:
    steps:
      - checkout
      - run:
          name: Set up Python
          command: pyenv global 3.9.9
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run isort
          command: isort .
      - run:
          name: Run black
          command: black .
      - run:
          name: Run tests
          command: pytest -k "not slow" # slowマークがないテストを実行
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run mypy
          command: mypy ./ --ignore-missing

  kaggle:
    docker:
      - image: some-base-image
    steps:
      - checkout
      - run:
          name: Set up Python
          command: pyenv global 3.9.9
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Create ZIP archive
          command: zip -r ./kaggle_datasets_git/mykaggle.zip * -x "kaggle_datasets_git/*" #kaggle_datasets_gitを除く全て
      - run:
          name: Upload to Kaggle dataset
          command: kaggle datasets version -p ./kaggle_datasets_git -m $CIRCLE_SHA1 -d

workflows:
  version: 2
  test:
    jobs:
      - test
  kaggle:
    jobs:
      - kaggle:
          filters:
            branches:
              only: master
