# Same as `code-quality-pr.yaml` but triggered on commit to main branch
# and runs on all files (instead of only the changed ones)

name: Code Quality Main

on:
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clear Python cache
        run: |
          sudo rm -rf $RUNNER_TOOL_CACHE/Python

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.x

      - name: Run pre-commits
        uses: pre-commit/action@v3
